@protocol = http
#@protocol = https
@host = localhost:8080
#@host = bncsbx-sbx-network-spatial-services-srv.cfapps.sap.hana.ondemand.com
#@host = bncsbx-sbx-nss-service.cfapps.sap.hana.ondemand.com
#@token = access_token

###Get GeoLocations
GET {{protocol}}://{{host}}/odata/v4/nss/GeoLocations?

###Get Config
GET {{protocol}}://{{host}}/odata/v4/geoconfig/getConfig()


###Get GeoService Metadata
GET {{protocol}}://{{host}}/odata/v4/geoservice/$metadata

###Get Geometries
GET {{protocol}}://{{host}}/odata/v4/geoservice/Geometries(id=296caa4e-f5fc-4c1a-9f17-ab68813bf4d4)

###Delete Geometry
DELETE {{protocol}}://{{host}}/odata/v4/geoservice/Geometries(id=a327f16b-307e-4720-a72d-3d0b5060885e)

###Update Geometry
PATCH {{protocol}}://{{host}}/odata/v4/geoservice/Geometries(id=296caa4e-f5fc-4c1a-9f17-ab68813bf4d4)
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "boReference_ID": "31de21af-8bef-4890-ac10-ce5b7307cba4",
  "boContext": "update to another BO"
}

###Get View BusinessGeometries
GET {{protocol}}://{{host}}/odata/v4/geoservice/BusinessGeometries


###Get BO
GET {{protocol}}://{{host}}/odata/v4/geoservice/BusinessObjects


###Get BO Expand
GET {{protocol}}://{{host}}/odata/v4/geoservice/BusinessObjects(ID=31de21af-8bef-4890-ac10-ce5b7307cba4)?$expand=geometries

###Delete BO
DELETE {{protocol}}://{{host}}/odata/v4/geoservice/BusinessObjects(ID=72578c46-196b-4fce-b2c6-da801fda8d72)

###Update BO
PATCH {{protocol}}://{{host}}/odata/v4/geoservice/BusinessObjects(ID=0dce19c2-93cf-40da-a259-c7a007028b4f)
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "boType": "TestBOTypeChange"
}

### Post BO w/o geometry
POST {{protocol}}://{{host}}/odata/v4/geoservice/BusinessObjects HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "boType": "WorkOrder",
  "appReferenceObjectId": "BOWOGeom1"
}

### Post BO with Geometry
POST {{protocol}}://{{host}}/odata/v4/geoservice/BusinessObjects HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "boType": "WorkOrder",
  "appReferenceObjectId": "TestJDBCAndHistory7",
  "geometries": [
    {
      "boGeometry": "{\"type\":\"Polygon\",\"coordinates\":[[[66.09375,44.08758502824516],[41.8359375,-17.978733095556155],[77.6953125,11.178401873711785],[91.0546875,40.44694705960048],[76.9921875,53.9560855309879],[66.09375,44.08758502824516]]]}",
      "boContext": "test geojson polygon",
      "metaData": "{\"refName\":\"Pole\", \"Type\":\"EquipmentObject3\"}"
    },
    {
      "boGeometry": "{\"type\":\"LineString\",\"coordinates\":[[-5.2734375,51.39920565355378],[-42.5390625,-4.565473550710278],[-7.03125,-51.835777520452474]]}",
      "boContext": "test geojson linestring2",
      "metaData": "{\"refName\":\"Pole\", \"Type\":\"EquipmentObject4\"}"
    } 
  ]
}

### Post Geometries
POST {{protocol}}://{{host}}/odata/v4/geoservice/Geometries HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "boReference_ID": "31de21af-8bef-4890-ac10-ce5b7307cba4",
  "boContext": "TestJDBC",
  "boGeometry": "{\"type\":\"LineString\",\"coordinates\":[[-5.2734375,51.39920565355378],[-42.5390625,-4.565473550710278],[-7.03125,-51.835777520452474]]}",
  "metaData": "{\"refName\":\"Pole\", \"Type\":\"EquipmentObject\"}"
}


### Post Scenarios
POST {{protocol}}://{{host}}/odata/v4/geoconfig/Scenarios HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "Scenario to Layers",
  "Description": "Test Scenario Description",
  "ToRenderer_ID" : "150e8ca2-43e2-4674-8b20-0f7f94353e47",
  "ToLayers" : [
    {"Layer_ID": "395b0f14-c776-4bec-bbbb-140fa0c7a0fd"}, 
    {"Layer_ID": "a28382ed-703c-4e7b-b3a5-a7f535c2f155"}
  ]
}

###Delete Scenarios
DELETE {{protocol}}://{{host}}/odata/v4/geoconfig/Scenarios(ID=adb9bc52-5271-4702-bfe5-0ae41c85a691)

### Post Application
POST {{protocol}}://{{host}}/odata/v4/geoconfig/Applications HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Name": "App1 AIN Eq screen",
  "Description": "AIN EQ SCREEN DESC",
  "ApplicationType_Code" : "AIN",
  "ScreenName" : "Equipment-Screen",
  "ToScenarios" : [
    {"Scenario_ID": "c5b4f0ba-b16e-433e-9495-1127864b7352"}
  ]
}
